# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Unit Tests"
  lane :unit_tests do
    scan(
      scheme: "TheCatPokedexApp",
      clean: true,
      devices: ["iPhone 16"],
      only_testing: ["TheCatPokedexAppTests"],
      output_types: "junit,html"
    )
  end

  desc "Run UI Tests"
  lane :ui_tests do
    scan(
      scheme: "TheCatPokedexApp",
      clean: true,
      devices: ["iPhone 16"],
      only_testing: ["TheCatPokedexAppUITests"],
      output_types: "junit,html"
    )
  end
end